name: Run Pytest

on:
  push:
    branches: 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10', '3.12', '3.13']  # Specify the Python versions you want to test

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .
          python3 -m pip install pytest

      - name: Run pytest
        run: |
          python3 -m pytest
